#!/usr/bin/env bash
# transfer file to a server

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
elif [[ "$#" -lt 4 ]]; then
    scp StrictHostKeyCheking=no "$1" "$3@$2":~/
else
    scp -i "$4" StrictHostKeyCheking=no "$1" "$3@$2":~/
fi
