#!/usr/bin/env bash
# script to install and configure nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx enable
service nginx start
