#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    Listening on port 80.
#    Includes X-Served-By in the response header
#    Returns index.html
#    Includes a custom 404 page
#    The header contains the hostname of the server

apt-get update && apt-get install -y nginx

mkdir -p /var/www/html

echo "<body 
        style='margin: 0;
        padding: 0;
        display: flex;
        align-items:center;
        justify-content: center'>
        <h1 style='color: #ee483e;'>Hello Alx School<h1/>
      <body/>" > /var/www/html/index.html

printf %s "<body 
        style='margin: 0;
        padding: 0;
        display: flex;
        align-items:center;
        justify-content: center'>
        <h1 style='color: #ee483e; margin-top: 5vh;'>Hello Alx School<h1/>
      <body/>" > /var/www/html/index.html

printf %s "<body 
        style='margin: 0;
        padding: 0;
        display: flex;
        align-items:center;
        justify-content: center'>
        <h1 style='color: #ee483e; margin-top: 50vh;'>What are you looking for huh!!<h1/>
      <body/>" > /var/www/html/error_page.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    error_page 404 /error_page.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
