#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get -y update && apt-get -y upgrade
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update && apt-get -y install haproxy

cp -a /etc/haproxy/haproxy.cfg{,.orig}
printf %s "\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 364620-web-01 54.160.92.153:80 check
    server 364620-web-02 54.166.141.214:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
