#!/usr/bin/env bash
#
# Write Bash (init) script 101-manage_my_process that
# manages manage_my_process. (both files need to be pushed to git)
# Requirements:
	# When passing the argument start:
	# Starts manage_my_process
	# Creates a file containing its PID in /var/run/my_process.pid
	# Displays manage_my_process started
	# When passing the argument stop:
	# Stops manage_my_process
	# Deletes the file /var/run/my_process.pid
	# Displays manage_my_process stopped
	# When passing the argument restart
	# Stops manage_my_process
	# Deletes the file /var/run/my_process.pid
	# Starts manage_my_process
	# Creates a file containing its PID in /var/run/my_process.pid
	# Displays manage_my_process restarted
	# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

pid_file=/var/run/my_process.pid
output_file=/tmp/my_process


case "$1" in
	"start")
		./manage_my_process &
		echo "$(pgrep -f manage_my_process)" > $pid_file
		echo "manage_my_process started"
		;;
	"stop")
		pkill -f manage_my_process
		rm -rf $output_file $pid_file
		echo "manage_my_process stopped"
		;;
	"restart")
		pkill -f manage_my_process
		rm -rf $output_file $pid_file
		./manage_my_process &
		echo "$(pgrep -f manage_my_process)" > $pid_file
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
