#!/usr/bin/env bash
# display "Best School" 10 times using while loop

count=1

while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo "Best School"
		echo "Hi"
		count=$((count+1))
		continue
	fi
	echo "Best School"
	count=$((count+1))
done
