#!/usr/bin/env bash
# Write a Bash script that displays:
#	 The content of the current directory
#	 In a list format
# 	 Where only the part of the name after the first dash is displayed (refer to the example)

files=$(ls)
for file in $files; do
	echo $file | cut -d '-' -f 2
done
