#!/usr/bin/env bash
#
cp /etc/hosts /tmp/hosts.new
sed -E 's/localhost\t127.0.0.1/localhost\t127.0.0.2/g' /tmp/hosts.new
sed -E 's/facebook.com\t157.240.11.35/facebook.com\t8.8.8.8/g' /tmp/hosts.new
cp -f /tmp/hosts.new /etc/hosts
