#!/usr/bin/env bash
# Bash script that configures an Ubuntu
# server with the below requirements.

cp /etc/hosts /tmp/hosts
echo "127.0.0.2		localhost" > /tmp/hosts
echo "8.8.8.8		facebook.com" >> /tmp/hosts
cp -f /tmp/hosts /etc/hosts
